SFTP_DIR = "C:/Users/gilnr/OneDrive/Ambiente de Trabalho/ITC Contract/GitHub/dagster-scaffold/my-dagster-project/data/SFTP/"
INPUT_DIR = "C:/Users/gilnr/OneDrive/Ambiente de Trabalho/ITC Contract/GitHub/dagster-scaffold/my-dagster-project/data/input/"
OUTPUT_DIR = "C:/Users/gilnr/OneDrive/Ambiente de Trabalho/ITC Contract/GitHub/dagster-scaffold/my-dagster-project/data/output/"
DUCKDB_DATABASE = "C:/Users/gilnr/OneDrive/Ambiente de Trabalho/ITC Contract/GitHub/dagster-scaffold/my-dagster-project/data/staging/data.duckdb"
METADATA_TABLE = "C:/Users/gilnr/OneDrive/Ambiente de Trabalho/ITC Contract/GitHub/dagster-scaffold/my-dagster-project/data/metadata/hight_metadata.xlsx"
LOCAL_DUCKDB = "C:/Users/gilnr/OneDrive/Ambiente de Trabalho/ITC Contract/GitHub/dagster-scaffold/my-dagster-project/io_database/local_duckdb_database.duckdb"
POLARS_PARQUET_DIR = "C:/Users/gilnr/OneDrive/Ambiente de Trabalho/ITC Contract/GitHub/dagster-scaffold/my-dagster-project/io_database"
